CREATE TABLE IF NOT EXISTS urls
(
    id              BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME urls_id_seq START WITH 1 INCREMENT BY 1),
    short_code      VARCHAR(10) UNIQUE NOT NULL,
    original_url    VARCHAR(2048)      NOT NULL,
    clicks          BIGINT                      DEFAULT 0 NOT NULL,
    created_at      TIMESTAMPTZ        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_clicked_at TIMESTAMPTZ,

    CONSTRAINT uk_short_code UNIQUE (short_code),
    CONSTRAINT check_original_url_length CHECK (length(original_url) <= 2048)
);

-- Indexes for performance
CREATE INDEX idx_urls_short_code ON urls (short_code);
CREATE INDEX idx_urls_created_at ON urls (created_at DESC);

-- Comments for documentation
COMMENT ON TABLE urls IS 'Stores URL shortening mappings';
COMMENT ON COLUMN urls.id IS 'Auto-incrementing primary key';
COMMENT ON COLUMN urls.short_code IS 'Base62 encoded short code';
COMMENT ON COLUMN urls.original_url IS 'Original long URL';
COMMENT ON COLUMN urls.clicks IS 'Number of times the short URL has been accessed';
COMMENT ON COLUMN urls.created_at IS 'Timestamp when the URL was created';
COMMENT ON COLUMN urls.last_clicked_at IS 'Timestamp of the last click';
